/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as StreamsRouteRouteImport } from './routes/streams.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamsIndexRouteImport } from './routes/streams.index'
import { Route as StreamsDefaultRouteImport } from './routes/streams.default'
import { Route as StreamsPiSessionIdRouteImport } from './routes/streams.$piSessionId'

const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsRouteRoute = StreamsRouteRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIndexRoute = StreamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StreamsRouteRoute,
} as any)
const StreamsDefaultRoute = StreamsDefaultRouteImport.update({
  id: '/default',
  path: '/default',
  getParentRoute: () => StreamsRouteRoute,
} as any)
const StreamsPiSessionIdRoute = StreamsPiSessionIdRouteImport.update({
  id: '/$piSessionId',
  path: '/$piSessionId',
  getParentRoute: () => StreamsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteRouteWithChildren
  '/runtime': typeof RuntimeRoute
  '/streams/$piSessionId': typeof StreamsPiSessionIdRoute
  '/streams/default': typeof StreamsDefaultRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runtime': typeof RuntimeRoute
  '/streams/$piSessionId': typeof StreamsPiSessionIdRoute
  '/streams/default': typeof StreamsDefaultRoute
  '/streams': typeof StreamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteRouteWithChildren
  '/runtime': typeof RuntimeRoute
  '/streams/$piSessionId': typeof StreamsPiSessionIdRoute
  '/streams/default': typeof StreamsDefaultRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/streams'
    | '/runtime'
    | '/streams/$piSessionId'
    | '/streams/default'
    | '/streams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runtime'
    | '/streams/$piSessionId'
    | '/streams/default'
    | '/streams'
  id:
    | '__root__'
    | '/'
    | '/streams'
    | '/runtime'
    | '/streams/$piSessionId'
    | '/streams/default'
    | '/streams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StreamsRouteRoute: typeof StreamsRouteRouteWithChildren
  RuntimeRoute: typeof RuntimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams': {
      id: '/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof StreamsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/': {
      id: '/streams/'
      path: '/'
      fullPath: '/streams/'
      preLoaderRoute: typeof StreamsIndexRouteImport
      parentRoute: typeof StreamsRouteRoute
    }
    '/streams/default': {
      id: '/streams/default'
      path: '/default'
      fullPath: '/streams/default'
      preLoaderRoute: typeof StreamsDefaultRouteImport
      parentRoute: typeof StreamsRouteRoute
    }
    '/streams/$piSessionId': {
      id: '/streams/$piSessionId'
      path: '/$piSessionId'
      fullPath: '/streams/$piSessionId'
      preLoaderRoute: typeof StreamsPiSessionIdRouteImport
      parentRoute: typeof StreamsRouteRoute
    }
  }
}

interface StreamsRouteRouteChildren {
  StreamsPiSessionIdRoute: typeof StreamsPiSessionIdRoute
  StreamsDefaultRoute: typeof StreamsDefaultRoute
  StreamsIndexRoute: typeof StreamsIndexRoute
}

const StreamsRouteRouteChildren: StreamsRouteRouteChildren = {
  StreamsPiSessionIdRoute: StreamsPiSessionIdRoute,
  StreamsDefaultRoute: StreamsDefaultRoute,
  StreamsIndexRoute: StreamsIndexRoute,
}

const StreamsRouteRouteWithChildren = StreamsRouteRoute._addFileChildren(
  StreamsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StreamsRouteRoute: StreamsRouteRouteWithChildren,
  RuntimeRoute: RuntimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
