/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as PiRouteRouteImport } from './routes/pi.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as PiIndexRouteImport } from './routes/pi.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as PiDefaultRouteImport } from './routes/pi.default'
import { Route as PiSessionIdRouteImport } from './routes/pi.$sessionId'

const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const PiRouteRoute = PiRouteRouteImport.update({
  id: '/pi',
  path: '/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PiIndexRoute = PiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PiRouteRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PiDefaultRoute = PiDefaultRouteImport.update({
  id: '/default',
  path: '/default',
  getParentRoute: () => PiRouteRoute,
} as any)
const PiSessionIdRoute = PiSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => PiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pi': typeof PiRouteRouteWithChildren
  '/runtime': typeof RuntimeRoute
  '/pi/$sessionId': typeof PiSessionIdRoute
  '/pi/default': typeof PiDefaultRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/pi/': typeof PiIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runtime': typeof RuntimeRoute
  '/pi/$sessionId': typeof PiSessionIdRoute
  '/pi/default': typeof PiDefaultRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/pi': typeof PiIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pi': typeof PiRouteRouteWithChildren
  '/runtime': typeof RuntimeRoute
  '/pi/$sessionId': typeof PiSessionIdRoute
  '/pi/default': typeof PiDefaultRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/pi/': typeof PiIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pi'
    | '/runtime'
    | '/pi/$sessionId'
    | '/pi/default'
    | '/sessions/$sessionId'
    | '/pi/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runtime'
    | '/pi/$sessionId'
    | '/pi/default'
    | '/sessions/$sessionId'
    | '/pi'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/pi'
    | '/runtime'
    | '/pi/$sessionId'
    | '/pi/default'
    | '/sessions/$sessionId'
    | '/pi/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PiRouteRoute: typeof PiRouteRouteWithChildren
  RuntimeRoute: typeof RuntimeRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi': {
      id: '/pi'
      path: '/pi'
      fullPath: '/pi'
      preLoaderRoute: typeof PiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi/': {
      id: '/pi/'
      path: '/'
      fullPath: '/pi/'
      preLoaderRoute: typeof PiIndexRouteImport
      parentRoute: typeof PiRouteRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi/default': {
      id: '/pi/default'
      path: '/default'
      fullPath: '/pi/default'
      preLoaderRoute: typeof PiDefaultRouteImport
      parentRoute: typeof PiRouteRoute
    }
    '/pi/$sessionId': {
      id: '/pi/$sessionId'
      path: '/$sessionId'
      fullPath: '/pi/$sessionId'
      preLoaderRoute: typeof PiSessionIdRouteImport
      parentRoute: typeof PiRouteRoute
    }
  }
}

interface PiRouteRouteChildren {
  PiSessionIdRoute: typeof PiSessionIdRoute
  PiDefaultRoute: typeof PiDefaultRoute
  PiIndexRoute: typeof PiIndexRoute
}

const PiRouteRouteChildren: PiRouteRouteChildren = {
  PiSessionIdRoute: PiSessionIdRoute,
  PiDefaultRoute: PiDefaultRoute,
  PiIndexRoute: PiIndexRoute,
}

const PiRouteRouteWithChildren =
  PiRouteRoute._addFileChildren(PiRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PiRouteRoute: PiRouteRouteWithChildren,
  RuntimeRoute: RuntimeRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
